name: Bug Report
description: Report a bug in Kuriyr
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Send a POST request to /send with ...
        2. Check the logs at ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide relevant environment details.
      placeholder: |
        - Kuriyr version: 0.2.8
        - Runtime: Bun 1.2 / Docker
        - OS: Ubuntu 24.04
        - Provider: SMTP / Resend
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any relevant log output.
      render: shell
    validations:
      required: false
